Traceback (most recent call last):
  File "/home/asimos/Documents/uff/aula/sd/trabs/rpc/question6/client.py", line 16, in <module>
    print(conn.root.sum_elements(v))
  File "/home/asimos/Documents/uff/aula/sd/trabs/rpc/rpcenv/lib/python3.9/site-packages/rpyc/core/netref.py", line 240, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/home/asimos/Documents/uff/aula/sd/trabs/rpc/rpcenv/lib/python3.9/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/asimos/Documents/uff/aula/sd/trabs/rpc/rpcenv/lib/python3.9/site-packages/rpyc/core/protocol.py", line 490, in sync_request
    return _async_res.value
  File "/home/asimos/Documents/uff/aula/sd/trabs/rpc/rpcenv/lib/python3.9/site-packages/rpyc/core/async_.py", line 106, in value
    self.wait()
  File "/home/asimos/Documents/uff/aula/sd/trabs/rpc/rpcenv/lib/python3.9/site-packages/rpyc/core/async_.py", line 55, in wait
    raise AsyncResultTimeout("result expired")
TimeoutError: result expired


NOTA: ao tentar tirar o timeout, o resultado n√£o retornou mesmo depois de 10 minutos
